feat: implement jwt using spring security
skku-comit/comit-website-spring-server pull request #6
Opened 2024-08-16 11:39 UTC by B0XERCAT

### Description
커밋 내역 확인하기 위해 임시로 올린 PR입니다

Closes #4 
### Additional context

2024-08-17 17:46 UTC, jihostudy approved these changes
LGTM!!

2024-08-17 17:46 UTC, jihostudy commented on src/test/http/admin/users.http
> +Authorization: Bearer {{access_token}}
Access Token은 Header - Authorization 확인했습니다!

2024-08-17 17:46 UTC, jihostudy commented on src/main/java/com/example/comitserver/jwt/LoginFilter.java
> +        response.addCookie(JWTUtil.createCookie("refresh", refreshToken));
refreshToken은 Cookie 확인했습니다! 고생하셨습니다

2024-08-17 18:20 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/jwt/LoginFilter.java
> +        response.addCookie(JWTUtil.createCookie("refresh", refreshToken));
감사합니다! 재순이 형도 approve 하면 바로 병합할게여~

2024-08-17 18:54 UTC, manamana32321 commented
고생 많으셨습니다.

그런데 JWT 정책에 관련해서 몇 가지 질문이 있습니다.
# 1. AT와 RT를 동시에 발급한다면 AT와 RT의 차이점은 무엇인가요?
동시에 발급할거면 하나의 토큰만 사용해서 httpOnly=true로 설정하고
클라이언트에서 개인화 된 정보(유저 ID, 유저 이름 등)를 사용해야 할 때에는 그 값을 httpOnly=false인 쿠키나 세션에 저장하면 되는 것 아닌가요?

# 2. RT 재발급 시 블랙리스트에 추가 방식에 대해
RT 재발급 시 블랙리스트에 추가가 된다면
시간이 흐를수록 DB에 블랙리스트가 쌓이며 되어 날이 갈수록 인증 시간이 늘어날 겁니다.
Java 코드를 제가 잘 이해하지 못해서 놓쳤을 수도 있는데
혹시 이처럼 누적되는 블랙리스트를 각 RT의 만료 기간에 맞추어 삭제하는 등의 보안책이 있나요?

# 3. DB에 RT를 저장하는 방식에 대해
AT와 RT를 동시에 재발급 하는 방식 + RT를 DB에 저장하는 것은 보안 측면에서는 아주 훌륭한 방식이라고 생각합니다.
하지만 동시에 컴퓨팅 리소스를 가장 많이 소비하는 방식인 것 같습니다.
게다가 DB에 RT를 저장하면서 무상태성의 이점을 잃어버립니다.
세션 방식과의 차이점이라면 매 요청마다 서버가 인증 여부 외의 세션 정보를 DB에서 불러오지 않아도 된다는 점이겠죠.

여기서 이 프로젝트의 성격을 고려해봅시다.
본 프로젝트는 현재 라즈베리 파이 서버 1개를 사용하며
동아리 웹페이지라는 특성 상 그 사용자 풀이 비교적 폐쇄적입니다.
DB에서 RT를 조회하게 되면 무상태성이 손실되며 서버 리소스 사용량이 늘어나게 됩니다.
사실상 세션 방식의 서버 리소스 사용량과 비슷하게 되는 것이죠.
라즈베리 파이 서버의 성능이 어떨지 정확히는 모르겠습니다만
RT를 DB에 저장하는 방식을 재고하여 서버 리소스 사용량을 최대한 줄이는 것은 어떨까요?
사용자 풀이 작고 폐쇄적이라 보안에 대한 중요성이 그렇게 크지는 않을 거라고 생각합니다.

제 이해력이 고장나서 질문이 많네요
답변 미리 감사합니다

2024-08-17 20:36 UTC, manamana32321 requested changes
정말 수고 많으셨습니다!!
덕분에 인증/인가라는 큰 과제가 하나 해결됐네요 :)
몇 가지 수정 사항만 확인해주시면 될 것 같습니다!

2024-08-17 20:36 UTC, manamana32321 commented on src/main/java/com/example/comitserver/service/JoinService.java
> +        Boolean isExist = userRepository.existsByEmail(email);
unique 조건 충족 여부를 확인해야 하는 필드들이 더 있습니다.
`studentId`, `phoneNumber`에 대한 unique 충족 여부를 확인해주세요.
그리고 `void`를 반환하는 것보다는 적절한 에러를 발생시키는 것이 좋아 보입니다.

2024-08-17 20:36 UTC, manamana32321 commented on src/main/java/com/example/comitserver/service/CustomUserDetailsService.java
> +public class CustomUserDetailsService implements UserDetailsService {
`UserService`와의 차이점이 무엇인가요?

2024-08-17 20:36 UTC, manamana32321 commented on src/main/java/com/example/comitserver/controller/JoinController.java
> +        return "ok";
다른 파일에서도 그랬던 것처럼 `ResponseEntity`를 반환하는 것이 통일성을 유지하는데 도움이 될 것 같습니다

2024-08-18 03:29 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/entity/UserEntity.java
> +}
JPA Auditing 이슈를 새로 파서 해보겠습니다!
https://webcoding-start.tistory.com/53
이런 느낌으로 해볼게여

2024-08-18 03:29 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/controller/UserAdminController.java
> +        userAdminService.updateUserRole(id, role);
넵 확인했습니다! 이것도 다음 이슈로 빼서 해볼게요!

2024-08-18 03:32 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/service/CustomUserDetailsService.java
> +public class CustomUserDetailsService implements UserDetailsService {
CustomUserDetailsService는 주로 Spring Security에서 인증과 관련된 사용자 세부 정보를 로드하는 데 사용됩니다. 사용자가 제공한 자격 증명에 따라 사용자의 세부 정보를 로드합니다!

2024-08-18 03:35 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/service/UserAdminService.java
> +                .orElseThrow(() -> new RuntimeException("User not found with id: " + id));
수정했습니다!

2024-08-18 03:35 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/entity/UserEntity.java
> +    @Column(unique = true)
수정했습니다!

2024-08-18 03:38 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/service/JoinService.java
> +        Boolean isExist = userRepository.existsByEmail(email);
수정했습니다

2024-08-18 03:42 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/controller/JoinController.java
> +        return "ok";
수정했습니다

2024-08-18 03:51 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/controller/UserAdminController.java
> +        userAdminService.updateUserRole(id, role);
마찬가지로 Exception을 던질 때에도 JSON 형태로 메시지를 줘야 할 것 같습니다!

2024-08-18 04:57 UTC, manamana32321 commented on src/main/java/com/example/comitserver/controller/UserAdminController.java
> +        userAdminService.updateUserRole(id, role);
> 마찬가지로 Exception을 던질 때에도 JSON 형태로 메시지를 줘야 할 것 같습니다!

[에러 및 응답 형태](https://github.com/skku-comit/comit-website/pull/126)를 참고하면 좋습니다~

2024-08-18 05:01 UTC, manamana32321 approved these changes
LGTM!

2024-08-18 06:59 UTC, merged

2024-08-20 09:17 UTC, winnercup1602 commented
제가 쉬는동안 너무나도 엄청난 발전이 있었네요!! 정말 고생 많으셨습니다!!