feat: add response DTO, add join validation
skku-comit/comit-website-spring-server pull request #9
Opened 2024-08-19 15:55 UTC by B0XERCAT

### Description

## 1. ServerErrorDTO와 ServerResponseDTO를 추가

```
{
    "data": {
        "id": 5,
        "username": "admin"
    },
    "error": null
}
```
```
{
    "data": null,
    "error": {
        "errorType": "401 Unauthorized",
        "title": "Authentication Failed",
        "detail": "Invalid email or password."
    }
}
```

모든 Response를 위와 같은 형태로 통일합니다

## 2. 회원가입 시 validation 추가
1. 비밀번호 6자 이상
2. 학번 반드시 10자 숫자
3. 전화번호는 반드시 숫자
4. 이메일 형식 준수
invalid 할 경우의 에러 핸들링 완료

### Additional context

2024-08-19 17:43 UTC, manamana32321 requested changes
[고생하셨습니다](https://youtu.be/4Z6rGw89bBs?si=1WHBba47V1oerWP_)

2024-08-19 17:43 UTC, manamana32321 commented on src/main/java/com/example/comitserver/jwt/LoginFilter.java
> +                    "401 Unauthorized",
이전에 회의에서 status 를 ResponseDTO에서 제외한 이유는
JSON 변환 전의 응답에서 이를 확인할 수 있기 때문이었습니다.
여기서도 `HttpStatus.UNAUTHORIZED` 에서 해당 정보를 확인할 수 있기에 `401 ` 부분은 지워도 될 것 같습니다!

다른 코드에서도 이런 패턴이 있던데 만약 지운다면 함께 수정하면 될 것 같습니다

2024-08-19 17:43 UTC, manamana32321 commented on src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
> +                    "400 Bad Request",
`ErrorResponse`는 `errorType`을 정의함으로서 동일한 `status`에서도 세밀한 에러 구분이 가능하다는 장점이 있습니다.
이 경우에서 그 장점을 발휘할 수 있습니다.
`errorType = "Auth/Logout/RefreshTokenExpired"`로 설정해 적용해볼 수 있습니다.

그리고 `errorType`를 사전 정의 및 구조화해서 `enum` 형태로 저장하는 것은 어떤가요?
프론트엔드 레포지토리의 `app/api/errors/types.ts`가 그 예시입니다.
더 자세한 정보는 `app/api/utils/response/README.md`를 참고해주세요

2024-08-19 17:43 UTC, manamana32321 commented on src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
> +                    "400 Bad Request",
`errorType = "Auth/Logout/InvalidTokenType`

2024-08-19 17:43 UTC, manamana32321 commented on src/main/java/com/example/comitserver/uitls/ResponseUtil.java
> +    public static void writeSuccessResponse(HttpServletResponse response, Object data) throws IOException {
[HTTP 상태 코드](https://developer.mozilla.org/ko/docs/Web/HTTP/Status#%EC%84%B1%EA%B3%B5_%EC%9D%91%EB%8B%B5)는 `200 OK` 이외에도 다른 값을 가질 수 있습니다.
리소스가 생성 됨을 알리는 `201 Created`가 대표적인 예시입니다.
이를 고려해서 위의 `writeErrorResponse`처럼 `HttpStatus status`를 인자로 받는 것이 좋아보입니다. :)

2024-08-19 18:44 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/jwt/LoginFilter.java
> +                    "401 Unauthorized",
errorType에서 statusCode는 전부 삭제했습니다!

2024-08-19 18:44 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
> +                    "400 Bad Request",
일단은 enum 대신 컨트롤러 경로를 참고해서 string 형태로 적는 방식으로 구현했습니다

2024-08-19 18:45 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
> +                    "400 Bad Request",
좋습니다~

2024-08-19 18:45 UTC, B0XERCAT commented on src/main/java/com/example/comitserver/uitls/ResponseUtil.java
> +    public static void writeSuccessResponse(HttpServletResponse response, Object data) throws IOException {
좋습니다! 수정 완료했습니다! 다만 저희는 204는 사용하면 안되겠네요

2024-08-19 18:45 UTC, manamana32321 approved these changes
LGTM Good night 😴

2024-08-19 18:46 UTC, merged

2024-08-20 01:24 UTC, jihostudy commented
`ServerErrorDTO` 와 `ServerResponseDTO` 확인했습니다 ~